language: node_js
node_js:
  - stable
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - iojs
  - iojs-v1.0.4
before_install:
  - npm install -g gulp
install:
  - npm install
script:
  - gulp test

